### ISSUE TITLE
exception with foreman 1.4

### ISSUE THREAD

**Issue by cristifalcas** [GregSutcliffe/foreman_column_view#7]
It seems it's not working with foreman 1.4.

I installed it like so:
yum install ruby193-rubygem-foreman_column_view  
service httpd restart

When I connect to foreman there is no extra tab in the hosts list. 

When I click one of the hosts I get the following exception:

Warning!
undefined method `reject' for nil:NilClass

If you feel this is an error with Foreman itself, please open a new issue with Foreman ticketing system, You would probably need to attach the Full trace and relevant log entries.
NoMethodError
undefined method `reject' for nil:NilClass
app/views/hosts/_overview.html.erb:18:in`_app_views_hosts__overview_html_erb__2940846528551098427_67405340'
app/views/hosts/show.html.erb:25:in `_app_views_hosts_show_html_erb___1825293817106228945_66122160'
app/models/concerns/foreman/thread_session.rb:33:in`clear_thread'
lib/middleware/catch_json_parse_errors.rb:9:in `call'
